brew "git"
brew "git-lfs"
brew "tmux"
brew "stow"
brew "wget"
brew "tree"
brew "fd"
brew "ripgrep"
brew "openssl"
brew "gnupg"

# Terminal
brew "zsh"
brew "fzf" # For fzf-tab zsh plugin
brew "thefuck"
cask "iterm2"
cask "alacritty"
brew "starship"
cask "font-fira-code-nerd-font"
brew "Adembc/homebrew-tap/lazyssh"
brew "lazygit"

# Docker, k8s, tf
brew "docker"
brew "colima"
brew "kubectl"
brew "kustomize"
brew "k9s"
brew "kubelogin"
brew "helm"
tap "hashicorp/tap"
brew "hashicorp/tap/terraform"

cask "tableplus"
cask "android-file-transfer"
cask "onyx"
cask "claude-code"
cask "codex"
brew "gemini-cli"
